### ISSUE TITLE
bundy-init fails with "component msgq failed to start" error 

### ISSUE THREAD

**Issue by kivarun** [bundy-dns/bundy#122]
INFO [bundy-init.init]: BUNDY_STARTING starting BUNDY: bundy 20110223 (BUNDY 1.2.0)
DEBUG [bundy-init.init]: BUNDY_CHECK_MSGQ_ALREADY_RUNNING checking if msgq is already running
INFO [bundy-init.init]: BUNDY_CONFIGURATOR_START bundy component configurator is starting up
DEBUG [bundy-init.init]: BUNDY_CONFIGURATOR_BUILD building plan '{}' -> '{'sockcreator': {'kind': 'core', 'special': 'sockcreator', 'priority': 200}, 'msgq': {'kind': 'core', 'special': 'msgq', 'priority': 199}, 'cfgmgr': {'kind': 'core', 'special': 'cfgmgr', 'priority': 198}}'
DEBUG [bundy-init.init]: BUNDY_CONFIGURATOR_RUN running plan of 3 tasks
DEBUG [bundy-init.init]: BUNDY_CONFIGURATOR_TASK performing task start on Socket creator
INFO [bundy-init.init]: BUNDY_COMPONENT_START component Socket creator is starting
INFO [bundy-init.init]: BUNDY_SOCKCREATOR_INIT initializing socket creator parser
DEBUG [bundy-init.init]: BUNDY_STARTED_PROCESS_PID started bundy-sockcreator (PID 11066)
DEBUG [bundy-init.init]: BUNDY_CONFIGURATOR_TASK performing task start on msgq
INFO [bundy-init.init]: BUNDY_COMPONENT_START component msgq is starting
INFO [bundy-init.init]: BUNDY_STARTING_PROCESS starting process bundy-msgq
DEBUG [bundy-init.init]: BUNDY_STARTED_PROCESS_PID started bundy-msgq (PID 11067)
ERROR [bundy-init.init]: BUNDY_COMPONENT_START_EXCEPTION component msgq failed to start: recv() on cc session timed out
ERROR [bundy-init.init]: BUNDY_COMPONENT_FAILED component msgq (pid None) failed: unknown condition
FATAL [bundy-init.init]: BUNDY_COMPONENT_UNSATISFIED component msgq is required to run and failed
ERROR [bundy-init.init]: BUNDY_CONFIGURATOR_PLAN_INTERRUPTED configurator plan interrupted, only 1 of 3 done
INFO [bundy-init.init]: BUNDY_KILLING_ALL_PROCESSES killing all started processes
INFO [bundy-init.init]: BUNDY_SEND_SIGKILL sending SIGKILL to Socket creator (PID 11066)
WARN [bundy-init.init]: BUNDY_SOCKCREATOR_KILL killing the socket creator
FATAL [bundy-init.init]: BUNDY_STARTUP_ERROR error during startup: Unable to start bundy-msgq: recv() on cc session timed out

Centos7, Python 3.6, log4cplus-1.1.3-0.4.rc3, botan-1.10.17-1 
configure options: CXXFLAGS="-std=gnu++11" ./configure --prefix=/opt/bundy

**Comment by shane-kerr** [comment]
Thanks for the report. I'll spin up a VM with CentOS 7 tomorrow and see if I can reproduce the problem.

**Comment by kivarun** [comment]
I managed to start the service. This problem is related previous issue, after fix it start  to work.

**Comment by shane-kerr** [comment]
Great!
