### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by yichunlan99** [bundy-dns/bundy#99]
i'm on centos7  x86_64.getting this at the end of the make.
/usr/local/python3.5/bin/python3 ../../../../../src/lib/util/python/gen_wiredata.py -o message_toText1.wire message_toText1.spec
Traceback (most recent call last):
  File "../../../../../src/lib/util/python/gen_wiredata.py", line 1368, in <module>
    obj.dump(output)
  File "../../../../../src/lib/util/python/gen_wiredata.py", line 715, in dump
    self.dump_header(f, self.rdlen)
  File "../../../../../src/lib/util/python/gen_wiredata.py", line 645, in dump_header
    rdlen_data = '%04x' % rdlen
TypeError: %x format: an integer is required, not float
make[7]: *** [message_toText1.wire] Error 1
make[7]: Leaving directory `/usr/local/src/bundy/src/lib/dns/tests/testdata'
make[6]: *** [all-recursive] Error 1
make[6]: Leaving directory `/usr/local/src/bundy/src/lib/dns/tests'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/usr/local/src/bundy/src/lib/dns'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/usr/local/src/bundy/src/lib/dns'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/usr/local/src/bundy/src/lib'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/local/src/bundy/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/local/src/bundy'
make: *** [all] Error 2

Configure command:
[root@localhost bundy]# ./configure --prefix=/usr/local/bundy --with-pythonpath=/usr/local/python3.5/bin/python3 --with-log4cplus=/usr/local/log4cplus/

**Comment by cstrotm** [comment]
Hi  yichunlan99, just tested this on CentOS 7 and can confirm the issue. I'll look into this.

**Comment by cstrotm** [comment]
Fixed with merged pull request #100
